# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            turkus 
tagline:          'site'
description:      'Impossible is nothing'
url:              http://turkus.github.io
baseurl:          /

author:
  name:           'Wojciech Rola'
  url:            https://turkus.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/turkus


socials:
  linkedin:       https://www.linkedin.com/in/turkus
  stackoverflow:  https://stackoverflow.com/users/6734406/turkus
  twitter:        https://twitter.com/WojciechRola
  facebook:       https://www.facebook.com/turkus
